import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Varela_Round } from "@next/font/google";
import NiceModal from "@ebay/nice-modal-react";
import { AddToastModal } from "~/modals/add-toast";
import { api } from "~/utils/api";
import { Button } from "~/components/ui/button";

const varelaRound = Varela_Round({ weight: ["400"], subsets: ["hebrew"] });

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  const { data } = api.toast.getAllByUser.useQuery();

  return (
    <>
      <Head>
        <title>אפלקציית מעקב שתיות</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${varelaRound.className} flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]`}
      >
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-center">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            אפלקציית מעקב{" "}
            <span className="text-[hsl(280,100%,70%)]">שתיות</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {sessionData && (
              <Button
                variant="secondary"
                onClick={() => void NiceModal.show(AddToastModal)}
              >
                הוספת שתיה
              </Button>
            )}
          </div>

          {data &&
            data.map(({ occasion: { name }, dateToBeDone, wasDone, id }) => (
              <div key={id} className="text-white">
                <span>{name}</span>
                <span>{dateToBeDone.toISOString()}</span>
                <span>{wasDone ? "✅" : "❌"}</span>
              </div>
            ))}
          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>מחובר כ {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "התנתק" : "התחבר"}
      </button>
    </div>
  );
};
